mysql:
  image: mysql:5.7
  ports:
    - '3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_DATABASE: 'wordpress'
    MYSQL_PASSWORD: 'root'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/
